require 'openstudio'
require 'openstudio-standards'
require 'rexml/document'
require 'rexml/xpath'

# require all .rb files in resources folder
# Dir[File.dirname(__FILE__) + '/resources/*/*.rb'].each { |file| require file }
require_relative 'resources/hvac_object'
require_relative 'resources/zone_hvac_equipment'
require_relative 'resources/acb'
require_relative 'resources/air_system'
require_relative 'resources/baseboard_convective'
require_relative 'resources/baseboard_radiant'
require_relative 'resources/cav_box'
require_relative 'resources/chilled_water_loop'
require_relative 'resources/condenser_loop'
require_relative 'resources/fpfc'
require_relative 'resources/gbxml_parser'
require_relative 'resources/helpers'
require_relative 'resources/hot_water_loop'
require_relative 'resources/model_manager'
require_relative 'resources/pcb'
require_relative 'resources/pfpb'
require_relative 'resources/ptac'
require_relative 'resources/pthp'
require_relative 'resources/radiant_panel'
require_relative 'resources/sfpb'
require_relative 'resources/unit_heater'
require_relative 'resources/unit_ventilator'
require_relative 'resources/vav_box'
require_relative 'resources/vrf_condenser'
require_relative 'resources/vrf_fan_coil_unit'
require_relative 'resources/wshp'
require_relative 'resources/zone'
